name: Run ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version:  # or the version of Node.js your project uses

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run ESLint
    - name: Run ESLint
      run: npx eslint . # Adjust the directory or files as needed
